### ISSUE TITLE
The 2.4 release breaks cypress in many repos

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud-libraries/nextcloud-axios#638]
The 2.4 release breaks cypress in many repos for some reason.
https://github.com/nextcloud/viewer/actions/runs/5989883555/job/16246600700
https://github.com/nextcloud/photos/actions/runs/5798646767/job/15717925031

_Originally posted by @skjnldsv in https://github.com/nextcloud-libraries/nextcloud-axios/issues/627#issuecomment-1694614122_

**Comment by susnux** [comment]
It provides correct exports, I guess the tests using imports but run as CJS instead of ESM?
In this case the using projects probably missing the jest transform for `@nextcloud/axios`.

(Its a pitty jest still does not support it oom)

**Comment by skjnldsv** [comment]
> In this case the using projects probably missing the jest transform for `@nextcloud/axios`.

Nope, Viewer doesn't even have jest :see_no_evil:

**Comment by feefladder** [comment]
Posting here since I think it is related:
I had an issue when developing my app.
I wanted to have an axios instance that makes external calls to another website, as well as the @nextcloud/axios instance provided by this library. This lead to an error that sometimes showed up and sometimes did not, depending on the order of installation:
- Works:
  1. comment out the `import axios from "axios"` and all external-axios related code
  2. Build using `npm run watch` (using Vite)
  3. un-comment all external-axios related code
- Error:
  1. un-comment all external-axios related code
  2. un-comment all @nextcloud/axios related code
  3. build using `npm run dev`/`npm run build`

So far so not-good, but how to solve this?
Well, it turns out `@nextcloud/axios` is built to include the line `const axios = require("axios")`, which leads to [this issue](https://github.com/axios/axios/issues/5613#issuecomment-1501402458). Indeed, by going into `node_modules/@nextcloud/axios/index.cjs` and changing to `const axios=require("axios").default` solves this issue.
![image](https://github.com/nextcloud-libraries/nextcloud-axios/assets/33122845/39510432-772e-48ad-be31-71a24649de55)

EDIT: Now I cannot reproduce this issue, regardless of whether I append `.default`....

**Comment by feefladder** [comment]
Alternatively,and I'm sure there is a better way:
in `package.json`, remove all references to the `cjs` file:
```json
"main": "dist/index.es.mjs",
  "types": "dist/index.d.ts",
  "exports": {
    ".": {
      "types": "./dist/index.d.ts",
      "import": "./dist/index.es.mjs",
      "default": "./dist/index.es.mjs"
    }
  },
```

**Comment by susnux** [comment]
I did not see any app with that issue anymore. So seems that all apps have found a solution.
